FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/api_server ./cmd/api

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/api_server .
RUN chmod +x ./api_server
CMD ["./api_server"]