FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/consumer_app ./cmd/consumer

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/consumer_app .
RUN chmod +x ./consumer_app
CMD ["./consumer_app"]